name: main

on:
  push:
    branches: [0.8.26-cont]
  pull_request:
    branches: [0.8.26-cont]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  SCCACHE_REGION: ${{ vars.SCCACHE_REGION }}
  SCCACHE_BUCKET: ${{ vars.SCCACHE_BUCKET }}
  SCCACHE_ENDPOINT: ${{ vars.SCCACHE_ENDPOINT }}
  SCCACHE_SERVER_PORT: ${{ vars.SCCACHE_SERVER_PORT }}
  SCCACHE_S3_USE_SSL: ${{ vars.SCCACHE_S3_USE_SSL }}
  RUSTC_WRAPPER: sccache

jobs:
  build-test-check-clippy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: cache rust toolchain
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-rust

      - name: install rust
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: stable
          components: clippy

      - name: setup rust cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-all-crates: "true"

      - name: use sccache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
        with:
          version: "${{ vars.SCCACHE_VERSION }}"

      - name: run cargo build main
        run: cargo build --all --release

      - name: run cargo test
        run: cargo test

      - name: run cargo check
        run: cargo check

      - name: run clippy
        run: cargo clippy --

  format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: cache rust toolchain
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-rust

      - name: install latest rust
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537 # master
        with:
          toolchain: stable
          components: rustfmt

      - name: format check
        run: cargo fmt -- --check

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: conventional commits
      uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
